### ISSUE TITLE
Correcciones memoria

### ISSUE THREAD

**Issue by alvarag** [bsc0001/TFG_Stroke-Detection-Prediction-UsingTCs#37]
Adjunto algunos cambios sugeridos en la memoria

[memoriaAAG.pdf](https://github.com/bsc0001/TFG_Stroke-Detection-Prediction-UsingTCs/files/3275233/memoriaAAG.pdf)

De anexos no he visto nada actualizado.

**Comment by bsc0001** [comment]
Lo reviso
