### ISSUE TITLE
Revisar los últimos 2 notebooks y el contenido del directorio extensions

### ISSUE THREAD

**Issue by bsc0001** [bsc0001/TFG_Stroke-Detection-Prediction-UsingTCs#47]
Queda un error que se puede ver en el notebook "Training_Test.ipynb" que no consigo solventar por más cambios que he probado, tanto en el fichero config.ini, como en la clase que he subido nueva de la red, e incluso por momentos en ficheros propios de niftynet.

_Originally posted by @bsc0001 in https://github.com/bsc0001/TFG_Stroke-Detection-Prediction-UsingTCs/issues/46#issuecomment-502204858_

Llevo un par de días con ello y no hay manera. Entendí que la segmentación última tenía sentido que diera error al no cuadrar el número de clases para el que yo lo configuraba con el del modelo de la red previamente entrenada que trataba de utilizarse. Pero me puse a tratar de entrenar un modelo y después de ir cuadrando varias cosas llevo todo el día atascada en este error. ¿Alguna idea?

https://niftynet.readthedocs.io/en/dev/extending_net.html
https://niftynet.readthedocs.io/en/dev/config_spec.html?
https://niftynet.readthedocs.io/en/latest/config_spec.html?

**Comment by alvarag** [comment]
El error parece que lo da por un parámetro: ```w_initializer```, ¿de dónde sale? ¿es un parámetro que has configurado tu en algún fichero de configuración o aparece dentro de su código?

**Comment by bsc0001** [comment]
Aparece dentro del código. En los enlace de documentación sobre el config file ni menciona ese parámetro, pero investigando más encontré que sí existe como parámetro cuya configuración es opcional y con un valor por defecto ("he_normal") en caso de no incluirlo específicamente. Esto es lo que pasaba en el caso de los TCs abdominales, no estaba incluido, pero al segmentar imprime por pantalla los valores que está usando, bien por la configuración o por defecto (https://nimb.ws/uton0N), tal como se ve en el notebook subido.
He probado a incluir este parámetro en el config file explícitamente, tanto con ese valor por defecto, como con otros que pude encontrar como aceptados: "zeros", "ones"... Pero no soluciona nada. Es más, si te fijas también en el notebook del intento de entrenamiento, antes de mostrar ese error sí que llega a procesar la configuración y mostrar por pantalla todos los parámentros que se usan para el entrenamiento y ahí figura que toma por defecto el normal sin problemas (https://nimb.ws/IrF8Bt).

**Comment by alvarag** [comment]
Habría que descubrir desde dónde se arrastra dicho parámetro. Por lo que yo veo de un análisis somero, ```iftynet/application/segmentation_application.py``` está fallando en la línea 280 porque encuentra un parámetro que no espera (```w_initializer```). Para poder ver por dónde van los parámetros, puede ser mejor tirar de bajarse el repositorio en otro entorno virtual y modificar con ```print``` alguno de los códigos de Niftynet.
Hay que saber cuál es la llamada de clases/métodos y ver cómo le llega ese parámetro.
